prompt --application/pages/page_01343
begin
--   Manifest
--     PAGE: 01343
--   Manifest End
wwv_flow_imp.component_begin (
 p_version_yyyy_mm_dd=>'2024.11.30'
,p_release=>'24.2.9'
,p_default_workspace_id=>31592798490575853
,p_default_application_id=>1000
,p_default_id_offset=>221683928681757931
,p_default_owner=>'TEMPLATE_APPV8'
);
wwv_flow_imp_page.create_page(
 p_id=>1343
,p_name=>'rptRGBLAccounts'
,p_step_title=>'Listing of RGBL Accounts'
,p_reload_on_submit=>'A'
,p_warn_on_unsaved_changes=>'N'
,p_first_item=>'AUTO_FIRST_ITEM'
,p_autocomplete_on_off=>'ON'
,p_group_id=>wwv_flow_imp.id(3825577329210146780)
,p_page_template_options=>'#DEFAULT#'
,p_required_role=>wwv_flow_imp.id(3825715219365210726)
,p_help_text=>'No help is available for this page.'
,p_page_component_map=>'18'
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(3740094078597765783)
,p_plug_name=>'Listing of Republic Bank Accounts'
,p_region_template_options=>'#DEFAULT#:t-Region--accent14:t-Region--scrollBody'
,p_component_template_options=>'#DEFAULT#'
,p_plug_template=>4072358936313175081
,p_plug_display_sequence=>10
,p_query_type=>'SQL'
,p_plug_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'select "PK_BANK_ACC_ID", ',
'"START_RANGE",',
'"END_RANGE",',
'"ACCOUNT_TYPE",',
'"CURRENCY",',
'"TRANSIT_NO",',
'"BANK_BRANCH_ID" "BANK_BRANCH_ID",',
'"LAST_CHANGED_BY",',
'"LAST_CHANGED_DATE",',
'"VERIFIED_BY",',
'"VERIFIED_DATE",',
'"ENTERED_BY",',
'"ENTRY_DATE",',
'"MACHINE_INSERT",',
'"MACHINE_UPDATE",',
'"TRANSACTION_TYPE_ID",',
'"STATUS"',
'from "#OWNER#"."PA_PCF_ACCOUNT" ',
'  '))
,p_plug_source_type=>'NATIVE_IR'
);
wwv_flow_imp_page.create_worksheet(
 p_id=>wwv_flow_imp.id(3740093879021765781)
,p_name=>'Listing of Republic Bank Accounts'
,p_max_row_count=>'1000000'
,p_max_row_count_message=>'The maximum row count for this report is #MAX_ROW_COUNT# rows.  Please apply a filter to reduce the number of records in your query.'
,p_no_data_found_message=>'No data found.'
,p_allow_save_rpt_public=>'Y'
,p_allow_report_categories=>'N'
,p_show_nulls_as=>'-'
,p_pagination_type=>'ROWS_X_TO_Y_OF_Z'
,p_pagination_display_pos=>'BOTTOM_RIGHT'
,p_show_display_row_count=>'Y'
,p_report_list_mode=>'TABS'
,p_lazy_loading=>false
,p_show_detail_link=>'C'
,p_show_rows_per_page=>'N'
,p_show_notify=>'Y'
,p_show_calendar=>'N'
,p_download_formats=>'CSV:HTML:PDF'
,p_enable_mail_download=>'Y'
,p_detail_link=>'f?p=&APP_ID.:1344:&SESSION.::&DEBUG.::P1344_PK_BANK_ACC_ID:#PK_BANK_ACC_ID#'
,p_detail_link_text=>'<img src="#IMAGE_PREFIX#app_ui/img/icons/apex-edit-pencil-alt.png" class="apex-edit-pencil-alt" alt="">'
,p_detail_link_auth_scheme=>wwv_flow_imp.id(3786032921827759264)
,p_allow_exclude_null_values=>'N'
,p_allow_hide_extra_columns=>'N'
,p_icon_view_columns_per_row=>1
,p_owner=>'PUR_INV'
,p_internal_uid=>134429215806979719
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(3829065078759508404)
,p_db_column_name=>'BANK_BRANCH_ID'
,p_display_order=>7
,p_column_identifier=>'G'
,p_column_label=>'Bank Branch'
,p_column_type=>'NUMBER'
,p_display_text_as=>'LOV_ESCAPE_SC'
,p_tz_dependent=>'N'
,p_static_id=>'BANK_BRANCH_ID'
,p_rpt_named_lov=>wwv_flow_imp.id(3854350106752385330)
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(3829064643135508403)
,p_db_column_name=>'LAST_CHANGED_DATE'
,p_display_order=>9
,p_column_identifier=>'I'
,p_column_label=>'Last Changed Date'
,p_column_type=>'DATE'
,p_tz_dependent=>'N'
,p_static_id=>'LAST_CHANGED_DATE'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(3829064282173508403)
,p_db_column_name=>'VERIFIED_DATE'
,p_display_order=>11
,p_column_identifier=>'K'
,p_column_label=>'Verified Date'
,p_column_type=>'DATE'
,p_tz_dependent=>'N'
,p_static_id=>'VERIFIED_DATE'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(3829063820896508402)
,p_db_column_name=>'ENTERED_BY'
,p_display_order=>12
,p_column_identifier=>'L'
,p_column_label=>'Entered By'
,p_column_type=>'STRING'
,p_tz_dependent=>'N'
,p_static_id=>'ENTERED_BY'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(3829063492441508402)
,p_db_column_name=>'ENTRY_DATE'
,p_display_order=>13
,p_column_identifier=>'M'
,p_column_label=>'Entry Date'
,p_column_type=>'DATE'
,p_tz_dependent=>'N'
,p_static_id=>'ENTRY_DATE'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(3829063078091508402)
,p_db_column_name=>'TRANSACTION_TYPE_ID'
,p_display_order=>16
,p_column_identifier=>'P'
,p_column_label=>'Transaction Type Id'
,p_column_type=>'NUMBER'
,p_tz_dependent=>'N'
,p_static_id=>'TRANSACTION_TYPE_ID'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(3829062653372508402)
,p_db_column_name=>'STATUS'
,p_display_order=>17
,p_column_identifier=>'Q'
,p_column_label=>'Status'
,p_column_type=>'STRING'
,p_tz_dependent=>'N'
,p_static_id=>'STATUS'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(3829062265941508400)
,p_db_column_name=>'PK_BANK_ACC_ID'
,p_display_order=>18
,p_column_identifier=>'R'
,p_column_label=>'Pk Bank Acc Id'
,p_column_type=>'NUMBER'
,p_column_alignment=>'RIGHT'
,p_tz_dependent=>'N'
,p_static_id=>'PK_BANK_ACC_ID'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(3829061804498508400)
,p_db_column_name=>'START_RANGE'
,p_display_order=>19
,p_column_identifier=>'S'
,p_column_label=>'Start Range'
,p_column_type=>'STRING'
,p_tz_dependent=>'N'
,p_static_id=>'START_RANGE'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(3829061419956508399)
,p_db_column_name=>'END_RANGE'
,p_display_order=>20
,p_column_identifier=>'T'
,p_column_label=>'End Range'
,p_column_type=>'STRING'
,p_tz_dependent=>'N'
,p_static_id=>'END_RANGE'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(3829061039893508398)
,p_db_column_name=>'ACCOUNT_TYPE'
,p_display_order=>21
,p_column_identifier=>'U'
,p_column_label=>'Account Type'
,p_column_type=>'STRING'
,p_tz_dependent=>'N'
,p_static_id=>'ACCOUNT_TYPE'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(3829060601584508398)
,p_db_column_name=>'CURRENCY'
,p_display_order=>22
,p_column_identifier=>'V'
,p_column_label=>'Currency'
,p_column_type=>'STRING'
,p_tz_dependent=>'N'
,p_static_id=>'CURRENCY'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(3829060211977508398)
,p_db_column_name=>'TRANSIT_NO'
,p_display_order=>23
,p_column_identifier=>'W'
,p_column_label=>'Transit No'
,p_column_type=>'STRING'
,p_tz_dependent=>'N'
,p_static_id=>'TRANSIT_NO'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(3829059838054508398)
,p_db_column_name=>'LAST_CHANGED_BY'
,p_display_order=>24
,p_column_identifier=>'X'
,p_column_label=>'Last Changed By'
,p_column_type=>'STRING'
,p_tz_dependent=>'N'
,p_static_id=>'LAST_CHANGED_BY'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(3829059472414508396)
,p_db_column_name=>'VERIFIED_BY'
,p_display_order=>25
,p_column_identifier=>'Y'
,p_column_label=>'Verified By'
,p_column_type=>'STRING'
,p_tz_dependent=>'N'
,p_static_id=>'VERIFIED_BY'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(3829059014087508395)
,p_db_column_name=>'MACHINE_INSERT'
,p_display_order=>26
,p_column_identifier=>'Z'
,p_column_label=>'Machine Insert'
,p_column_type=>'STRING'
,p_tz_dependent=>'N'
,p_static_id=>'MACHINE_INSERT'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(3829058624483508395)
,p_db_column_name=>'MACHINE_UPDATE'
,p_display_order=>27
,p_column_identifier=>'AA'
,p_column_label=>'Machine Update'
,p_column_type=>'STRING'
,p_tz_dependent=>'N'
,p_static_id=>'MACHINE_UPDATE'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_rpt(
 p_id=>wwv_flow_imp.id(3740090573018762310)
,p_application_user=>'APXWS_DEFAULT'
,p_report_seq=>10
,p_report_alias=>'454648'
,p_status=>'PUBLIC'
,p_is_default=>'Y'
,p_display_rows=>20
,p_report_columns=>'BANK_BRANCH_ID:ACCOUNT_TYPE:CURRENCY:TRANSIT_NO:START_RANGE:END_RANGE:STATUS:VERIFIED_BY:VERIFIED_DATE:'
,p_break_on=>'BANK_BRANCH_ID:0:0:0:0:0'
,p_break_enabled_on=>'BANK_BRANCH_ID:0:0:0:0:0'
);
wwv_flow_imp_page.create_page_button(
 p_id=>wwv_flow_imp.id(3829057453134508390)
,p_button_sequence=>10
,p_button_plug_id=>wwv_flow_imp.id(3740094078597765783)
,p_button_name=>'RETURN'
,p_button_action=>'REDIRECT_PAGE'
,p_button_template_options=>'#DEFAULT#:t-Button--primary'
,p_button_template_id=>4072362960822175091
,p_button_image_alt=>'Return'
,p_button_position=>'EDIT'
,p_button_redirect_url=>'f?p=&APP_ID.:1:&SESSION.::&DEBUG.:::'
);
wwv_flow_imp_page.create_page_button(
 p_id=>wwv_flow_imp.id(3847621394301605812)
,p_button_sequence=>20
,p_button_plug_id=>wwv_flow_imp.id(3740094078597765783)
,p_button_name=>'BANK_BRANCHES'
,p_button_action=>'REDIRECT_PAGE'
,p_button_template_options=>'#DEFAULT#'
,p_button_template_id=>4072362960822175091
,p_button_is_hot=>'Y'
,p_button_image_alt=>'Bank Branches'
,p_button_position=>'EDIT'
,p_button_redirect_url=>'f?p=&APP_ID.:1310:&SESSION.::&DEBUG.:RP:P1310_ORGANISATION:BANK'
);
wwv_flow_imp_page.create_page_button(
 p_id=>wwv_flow_imp.id(3829057866319508394)
,p_button_sequence=>30
,p_button_plug_id=>wwv_flow_imp.id(3740094078597765783)
,p_button_name=>'CREATE'
,p_button_action=>'REDIRECT_PAGE'
,p_button_template_options=>'#DEFAULT#:t-Button--success'
,p_button_template_id=>4072362960822175091
,p_button_image_alt=>'Add New'
,p_button_position=>'EDIT'
,p_button_redirect_url=>'f?p=&APP_ID.:1344:&SESSION.::&DEBUG.:1344::'
,p_security_scheme=>wwv_flow_imp.id(3807019444763118136)
);
wwv_flow_imp_page.create_page_da_event(
 p_id=>wwv_flow_imp.id(3829057126662508390)
,p_name=>'Refresh - Create'
,p_event_sequence=>10
,p_triggering_element_type=>'BUTTON'
,p_triggering_button_id=>wwv_flow_imp.id(3829057866319508394)
,p_bind_type=>'bind'
,p_execution_type=>'IMMEDIATE'
,p_bind_event_type=>'apexafterclosedialog'
);
wwv_flow_imp_page.create_page_da_action(
 p_id=>wwv_flow_imp.id(3829056632560508388)
,p_event_id=>wwv_flow_imp.id(3829057126662508390)
,p_event_result=>'TRUE'
,p_action_sequence=>10
,p_execute_on_page_init=>'N'
,p_action=>'NATIVE_REFRESH'
,p_affected_elements_type=>'REGION'
,p_affected_region_id=>wwv_flow_imp.id(3740094078597765783)
,p_attribute_01=>'N'
);
wwv_flow_imp_page.create_page_da_event(
 p_id=>wwv_flow_imp.id(3829056246718508387)
,p_name=>'Refresh - Edit'
,p_event_sequence=>20
,p_triggering_element_type=>'REGION'
,p_triggering_region_id=>wwv_flow_imp.id(3740094078597765783)
,p_bind_type=>'bind'
,p_execution_type=>'IMMEDIATE'
,p_bind_event_type=>'apexafterclosedialog'
);
wwv_flow_imp_page.create_page_da_action(
 p_id=>wwv_flow_imp.id(3829055750380508387)
,p_event_id=>wwv_flow_imp.id(3829056246718508387)
,p_event_result=>'TRUE'
,p_action_sequence=>10
,p_execute_on_page_init=>'N'
,p_action=>'NATIVE_REFRESH'
,p_affected_elements_type=>'REGION'
,p_affected_region_id=>wwv_flow_imp.id(3740094078597765783)
,p_attribute_01=>'N'
);
wwv_flow_imp.component_end;
end;
/
