prompt --application/pages/page_06004
begin
--   Manifest
--     PAGE: 06004
--   Manifest End
wwv_flow_imp.component_begin (
 p_version_yyyy_mm_dd=>'2024.11.30'
,p_release=>'24.2.8'
,p_default_workspace_id=>31592798490575853
,p_default_application_id=>120
,p_default_id_offset=>188895268110624634
,p_default_owner=>'TEMPLATE_APPV8'
);
wwv_flow_imp_page.create_page(
 p_id=>6004
,p_name=>'rptmonthlyprevytd'
,p_alias=>'RPTMONTHLYPREVYTD'
,p_step_title=>'rptmonthlyprevytd'
,p_autocomplete_on_off=>'OFF'
,p_group_id=>wwv_flow_imp.id(3603892880938383493)
,p_page_template_options=>'#DEFAULT#'
,p_protection_level=>'C'
,p_page_component_map=>'18'
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(462245697710934311)
,p_plug_name=>'Listing of Monthly Previous YTD'
,p_region_template_options=>'#DEFAULT#:t-Region--accent4:t-Region--scrollBody'
,p_plug_template=>4072358936313175081
,p_plug_display_sequence=>25
,p_query_type=>'TABLE'
,p_query_table=>'AYTD_OLD_PAYROLLDATA_M'
,p_include_rowid_column=>false
,p_plug_source_type=>'NATIVE_IR'
,p_prn_content_disposition=>'ATTACHMENT'
,p_prn_units=>'INCHES'
,p_prn_paper_size=>'LETTER'
,p_prn_width=>11
,p_prn_height=>8.5
,p_prn_orientation=>'HORIZONTAL'
,p_prn_page_header=>'Listing of Monthly Previous YTD'
,p_prn_page_header_font_color=>'#000000'
,p_prn_page_header_font_family=>'Helvetica'
,p_prn_page_header_font_weight=>'normal'
,p_prn_page_header_font_size=>'12'
,p_prn_page_footer_font_color=>'#000000'
,p_prn_page_footer_font_family=>'Helvetica'
,p_prn_page_footer_font_weight=>'normal'
,p_prn_page_footer_font_size=>'12'
,p_prn_header_bg_color=>'#EEEEEE'
,p_prn_header_font_color=>'#000000'
,p_prn_header_font_family=>'Helvetica'
,p_prn_header_font_weight=>'bold'
,p_prn_header_font_size=>'10'
,p_prn_body_bg_color=>'#FFFFFF'
,p_prn_body_font_color=>'#000000'
,p_prn_body_font_family=>'Helvetica'
,p_prn_body_font_weight=>'normal'
,p_prn_body_font_size=>'10'
,p_prn_border_width=>.5
,p_prn_page_header_alignment=>'CENTER'
,p_prn_page_footer_alignment=>'CENTER'
,p_prn_border_color=>'#666666'
);
wwv_flow_imp_page.create_worksheet(
 p_id=>wwv_flow_imp.id(462245800312934311)
,p_name=>'rptmonthlyprevytd'
,p_max_row_count_message=>'The maximum row count for this report is #MAX_ROW_COUNT# rows.  Please apply a filter to reduce the number of records in your query.'
,p_no_data_found_message=>'No data found.'
,p_allow_save_rpt_public=>'Y'
,p_pagination_type=>'ROWS_X_TO_Y'
,p_pagination_display_pos=>'BOTTOM_RIGHT'
,p_show_display_row_count=>'Y'
,p_report_list_mode=>'TABS'
,p_lazy_loading=>false
,p_show_detail_link=>'N'
,p_show_rows_per_page=>'N'
,p_show_notify=>'Y'
,p_download_formats=>'CSV:HTML:XLSX:PDF'
,p_enable_mail_download=>'Y'
,p_owner=>'SHIRAMAN'
,p_internal_uid=>40453807114937737
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(462246110780934482)
,p_db_column_name=>'NIB_NO'
,p_display_order=>1
,p_column_identifier=>'A'
,p_column_label=>'Nib No'
,p_column_type=>'NUMBER'
,p_heading_alignment=>'RIGHT'
,p_column_alignment=>'RIGHT'
,p_format_mask=>'999G999G999G999G999G999G999G999G999G990'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(462246575106934485)
,p_db_column_name=>'SURNAME'
,p_display_order=>2
,p_column_identifier=>'B'
,p_column_label=>'Surname'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(462246988166934485)
,p_db_column_name=>'FIRST_NAME'
,p_display_order=>3
,p_column_identifier=>'C'
,p_column_label=>'First Name'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(462247322810934485)
,p_db_column_name=>'NIB_EMPLOYEE'
,p_display_order=>4
,p_column_identifier=>'D'
,p_column_label=>'Nib Employee'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(462247786268934485)
,p_db_column_name=>'NIB_EMPLOYER'
,p_display_order=>5
,p_column_identifier=>'E'
,p_column_label=>'Nib Employer'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(462248099672934486)
,p_db_column_name=>'MEDICAL_EMPLOYEE'
,p_display_order=>6
,p_column_identifier=>'F'
,p_column_label=>'Medical Employee'
,p_column_type=>'NUMBER'
,p_heading_alignment=>'RIGHT'
,p_column_alignment=>'RIGHT'
,p_format_mask=>'999G999G999G999G999G999G999G999G999G990D00'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(462248547060934486)
,p_db_column_name=>'MEDICAL_EMPLOYER'
,p_display_order=>7
,p_column_identifier=>'G'
,p_column_label=>'Medical Employer'
,p_column_type=>'NUMBER'
,p_heading_alignment=>'RIGHT'
,p_column_alignment=>'RIGHT'
,p_format_mask=>'999G999G999G999G999G999G999G999G999G990D00'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(462248986665934486)
,p_db_column_name=>'MISC_INCOME'
,p_display_order=>8
,p_column_identifier=>'H'
,p_column_label=>'Misc Income'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(462249332320934486)
,p_db_column_name=>'DESCRIPTION'
,p_display_order=>9
,p_column_identifier=>'I'
,p_column_label=>'Description'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(462249727085934487)
,p_db_column_name=>'MISC_INCOME_NN'
,p_display_order=>10
,p_column_identifier=>'J'
,p_column_label=>'Misc Income Nn'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(462250113401934487)
,p_db_column_name=>'DESCRIPTION2'
,p_display_order=>11
,p_column_identifier=>'K'
,p_column_label=>'Description2'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(462250544608934487)
,p_db_column_name=>'MISC_DEDUCTION'
,p_display_order=>12
,p_column_identifier=>'L'
,p_column_label=>'Misc Deduction'
,p_column_type=>'NUMBER'
,p_heading_alignment=>'RIGHT'
,p_column_alignment=>'RIGHT'
,p_format_mask=>'999G999G999G999G999G999G999G999G999G990D00'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(462250911065934487)
,p_db_column_name=>'DESCRIPTION3'
,p_display_order=>13
,p_column_identifier=>'M'
,p_column_label=>'Description3'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(462251344853934488)
,p_db_column_name=>'MISC_DEDUCTION_NN'
,p_display_order=>14
,p_column_identifier=>'N'
,p_column_label=>'Misc Deduction Nn'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(462251775291934488)
,p_db_column_name=>'DESCRIPTION4'
,p_display_order=>15
,p_column_identifier=>'O'
,p_column_label=>'Description4'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(462252184750934488)
,p_db_column_name=>'SICK'
,p_display_order=>16
,p_column_identifier=>'P'
,p_column_label=>'Sick'
,p_column_type=>'NUMBER'
,p_heading_alignment=>'RIGHT'
,p_column_alignment=>'RIGHT'
,p_format_mask=>'999G999G999G999G999G999G999G999G999G990D00'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(462252520690934488)
,p_db_column_name=>'VACATION'
,p_display_order=>17
,p_column_identifier=>'Q'
,p_column_label=>'Vacation'
,p_column_type=>'NUMBER'
,p_heading_alignment=>'RIGHT'
,p_column_alignment=>'RIGHT'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(462252949699934488)
,p_db_column_name=>'REG_HRLY_P'
,p_display_order=>18
,p_column_identifier=>'R'
,p_column_label=>'Reg Hrly P'
,p_column_type=>'NUMBER'
,p_heading_alignment=>'RIGHT'
,p_column_alignment=>'RIGHT'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(462253345407934489)
,p_db_column_name=>'REG_HRLY_NN'
,p_display_order=>19
,p_column_identifier=>'S'
,p_column_label=>'Reg Hrly Nn'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(462253727253934489)
,p_db_column_name=>'EMPLOYEE_MEAL'
,p_display_order=>20
,p_column_identifier=>'T'
,p_column_label=>'Employee Meal'
,p_column_type=>'NUMBER'
,p_heading_alignment=>'RIGHT'
,p_column_alignment=>'RIGHT'
,p_format_mask=>'999G999G999G999G999G999G999G999G999G990'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(462254176642934489)
,p_db_column_name=>'OVERTIME_15'
,p_display_order=>21
,p_column_identifier=>'U'
,p_column_label=>'Overtime 15'
,p_column_type=>'NUMBER'
,p_heading_alignment=>'RIGHT'
,p_column_alignment=>'RIGHT'
,p_format_mask=>'999G999G999G999G999G999G999G999G999G990D00'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(462254526432934489)
,p_db_column_name=>'OVERTIME_15_NN'
,p_display_order=>22
,p_column_identifier=>'V'
,p_column_label=>'Overtime 15 Nn'
,p_column_type=>'NUMBER'
,p_heading_alignment=>'RIGHT'
,p_column_alignment=>'RIGHT'
,p_format_mask=>'999G999G999G999G999G999G999G999G999G990'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(462254938815934490)
,p_db_column_name=>'DOUBLETIME_N'
,p_display_order=>23
,p_column_identifier=>'W'
,p_column_label=>'Doubletime N'
,p_column_type=>'NUMBER'
,p_heading_alignment=>'RIGHT'
,p_column_alignment=>'RIGHT'
,p_format_mask=>'999G999G999G999G999G999G999G999G999G990D00'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(462255293268934490)
,p_db_column_name=>'DOUBLETIME_NN'
,p_display_order=>24
,p_column_identifier=>'X'
,p_column_label=>'Doubletime Nn'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(462255715576934490)
,p_db_column_name=>'PAID_HOLIDAY_N'
,p_display_order=>25
,p_column_identifier=>'Y'
,p_column_label=>'Paid Holiday N'
,p_column_type=>'NUMBER'
,p_heading_alignment=>'RIGHT'
,p_column_alignment=>'RIGHT'
,p_format_mask=>'999G999G999G999G999G999G999G999G999G990D00'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(462256186952934490)
,p_db_column_name=>'DOUBLE_HOLIDAY_NN'
,p_display_order=>26
,p_column_identifier=>'Z'
,p_column_label=>'Double Holiday Nn'
,p_column_type=>'NUMBER'
,p_heading_alignment=>'RIGHT'
,p_column_alignment=>'RIGHT'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(462256508173934491)
,p_db_column_name=>'EMP_ID'
,p_display_order=>27
,p_column_identifier=>'AA'
,p_column_label=>'Emp ID'
,p_column_type=>'NUMBER'
,p_heading_alignment=>'RIGHT'
,p_column_alignment=>'RIGHT'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(462256961188934491)
,p_db_column_name=>'EMPLOYEE_NO'
,p_display_order=>28
,p_column_identifier=>'AB'
,p_column_label=>'Employee No'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(462257321676934491)
,p_db_column_name=>'SAL_PAY'
,p_display_order=>29
,p_column_identifier=>'AC'
,p_column_label=>'Sal Pay'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(462257755843934492)
,p_db_column_name=>'SAL_PAY_NN'
,p_display_order=>30
,p_column_identifier=>'AD'
,p_column_label=>'Sal Pay Nn'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(462258156177934492)
,p_db_column_name=>'PAID_HOLIDAY'
,p_display_order=>31
,p_column_identifier=>'AE'
,p_column_label=>'Paid Holiday'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(462258547499934492)
,p_db_column_name=>'VACATION_PAID_NN'
,p_display_order=>32
,p_column_identifier=>'AF'
,p_column_label=>'Vacation Paid Nn'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(462258966425934492)
,p_db_column_name=>'VACATION_PAID_N'
,p_display_order=>33
,p_column_identifier=>'AG'
,p_column_label=>'Vacation Paid N'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_rpt(
 p_id=>wwv_flow_imp.id(462267143457979204)
,p_application_user=>'APXWS_DEFAULT'
,p_report_seq=>10
,p_report_alias=>'404752'
,p_status=>'PUBLIC'
,p_is_default=>'Y'
,p_report_columns=>'NIB_NO:SURNAME:FIRST_NAME:NIB_EMPLOYEE:NIB_EMPLOYER:MEDICAL_EMPLOYEE:MEDICAL_EMPLOYER:MISC_INCOME:DESCRIPTION:MISC_INCOME_NN:DESCRIPTION2:MISC_DEDUCTION:DESCRIPTION3:MISC_DEDUCTION_NN:DESCRIPTION4:SICK:VACATION:REG_HRLY_P:REG_HRLY_NN:EMPLOYEE_MEAL:OV'
||'ERTIME_15:OVERTIME_15_NN:DOUBLETIME_N:DOUBLETIME_NN:PAID_HOLIDAY_N:DOUBLE_HOLIDAY_NN:EMP_ID:EMPLOYEE_NO:SAL_PAY:SAL_PAY_NN:PAID_HOLIDAY:VACATION_PAID_NN:VACATION_PAID_N'
);
wwv_flow_imp_page.create_page_button(
 p_id=>wwv_flow_imp.id(462259663109937276)
,p_button_sequence=>10
,p_button_plug_id=>wwv_flow_imp.id(462245697710934311)
,p_button_name=>'CANCEL'
,p_button_action=>'REDIRECT_PAGE'
,p_button_template_options=>'#DEFAULT#:t-Button--mobileHideLabel:t-Button--iconRight'
,p_button_template_id=>2082829544945815391
,p_button_image_alt=>'Return'
,p_button_position=>'EDIT'
,p_button_alignment=>'RIGHT'
,p_button_redirect_url=>'f?p=&APP_ID.:1332:&SESSION.::&DEBUG.:::'
,p_icon_css_classes=>'fa-backwards'
);
wwv_flow_imp.component_end;
end;
/
