prompt --application/shared_components/security/authentications/custom
begin
--   Manifest
--     AUTHENTICATION: Custom
--   Manifest End
wwv_flow_imp.component_begin (
 p_version_yyyy_mm_dd=>'2024.11.30'
,p_release=>'24.2.7'
,p_default_workspace_id=>31592798490575853
,p_default_application_id=>112
,p_default_id_offset=>115784133856313705
,p_default_owner=>'TEMPLATE_APPV8'
);
wwv_flow_imp_shared.create_authentication(
 p_id=>wwv_flow_imp.id(3305289463095400608)
,p_name=>'Custom'
,p_scheme_type=>'NATIVE_CUSTOM'
,p_attribute_03=>'pkg_security.authenticate'
,p_attribute_05=>'N'
,p_plsql_code=>wwv_flow_string.join(wwv_flow_t_varchar2(
'procedure POST_AUTHENTICATION is',
'',
'   v_startpage varchar2(20); v_wkloc  number;  v_cyear  number;  v_nis  number;  v_tax   number; v_org_rule  number;',
'   v_orgstructure number;   v_job number;   v_grade  number;  v_pos  number;  v_pos_loc   number; v_org number;',
'   v_chk_wiz varchar2(1); v_max_id number; v_max_nisid number; v_max_orgstr number; v_max_job number; v_max_pos number;',
'   v_current_org number; v_load_home varchar2(50);  v_roles tblloginuserlog.roles%type:=''''; v_ori_org_id number;',
'   v_Password_Duration number:=0; v_due_date date;',
'',
'begin',
'',
'        begin',
'',
'                select Password_Duration, password_last_change + Password_Duration',
'                into v_Password_Duration, v_due_date',
'                from tbluser',
'                where user_name = :APP_USER',
'                and trunc(password_last_change) !=trunc(current_date);',
'',
'         exception',
'            when others then null;',
'        end;',
'       ',
'if v_Password_Duration > 0 then',
'            if trunc(current_date) > v_due_date then ',
'               :FSP_AFTER_LOGIN_URL := ''f?p=''||:APP_ID||'':199:''||:APP_SESSION||''::NO:::'';',
'               :GET_PWD_DURATION:=''CHANGE_PWD'';',
'            end if;',
'',
'else',
'          :GET_PWD_DURATION:='''';',
'',
'begin',
'    SELECT DISPLAY_WIZARD into v_chk_wiz',
'    From Tbluser',
'    WHERE UPPER(user_name)=UPPER(:P101_USERNAME)',
'    AND DISPLAY_WIZARD=''Y'';',
'',
'    select distinct pkg_global_fnts.fn_shareRefOrg(ORG_ID), org_id into v_current_org, v_ori_org_id',
'    from vw_useraccess',
'    where rownum=1;',
'    ',
'exception',
'    when others then ',
'      v_chk_wiz :=''N'';',
'end;',
' ',
'',
'    ',
'begin      ',
'',
' for I in (select RESPONSIBILITY_NAME||'' Dated:-''||b.EFFECTIVE_FROM resp_role',
'           from tbluser a join tbluserdetail b on a.user_id=b.user_id',
'           join tblresponsibility c on c.responsibility_id=b.responsibility_id',
'           where org_id = v_ori_org_id',
'           and  trunc(b.effective_from) <= trunc(current_date)',
'           and (TRUNC(b.effective_to) IS NULL OR TRUNC(b.effective_to) >= TRUNC(current_date))',
'           and trim(user_name)= nvl(V(''APP_USER''),USER)  ) loop',
'           ',
'           v_roles := v_roles||'', ''||i.resp_role;',
'                     ',
'  end loop;           ',
'/*',
'    update TBLLOGINUSERLOG',
'    set roles = v_roles',
'    where extract(hour from LOGIN_DATE_TIME) = TO_CHAR( current_date, ''HH24'' )',
'    and extract(minute from LOGIN_DATE_TIME) >TO_CHAR( current_date, ''MI'' ) -15',
'    and APP_USER=:APP_USER',
'    and trunc(LOGIN_DATE_TIME)=trunc(current_date);',
'*/    ',
'    delete',
'    from TBLLOGINUSERLOG',
'    where APP_USER=''SYS'';',
'',
'exception',
' when others then null;',
'end;',
'',
'    select trim(load_home) into   v_load_home',
'    from tbluser',
'    where USER_NAME =:APP_USER;',
'',
'    SELECT count(1) INTO v_org',
'    FROM HR_HCF_ORGANISATION',
'    where id=v_ori_org_id;',
'    ',
'    SELECT count(1) INTO v_wkloc',
'    FROM HR_HCF_WORKLOCATION',
'    where org_id=v_ori_org_id;',
'    ',
'    SELECT count(1) into v_cyear',
'    FROM HR_HCF_COMPANYYEAR',
'    WHERE org_id=v_ori_org_id;',
'    ',
'    SELECT count(1) into v_nis',
'    FROM HR_HCF_NISRATE',
'    WHERE org_id=v_current_org;',
'    ',
'    SELECT count(1) into v_tax ',
'    FROM HR_HCF_TAXRATE',
'    WHERE org_id=v_current_org;',
'',
'    SELECT count(1) into v_org_rule',
'    FROM HR_HCF_ORG_RULE',
'    where org_id=v_ori_org_id;',
'',
'    SELECT count(1) into v_orgstructure',
'    FROM HR_HCF_ORGSTRUCTUREDTL a',
'    WHERE EXISTS(SELECT 1',
'                 FROM HR_HCF_ORGSTRUCTUREHD b',
'                 WHERE org_id=v_current_org',
'                 and a.ORG_STRUCTURE_ID=b.id);',
'                 ',
'    SELECT count(1) into v_grade',
'    FROM HR_HCF_POSITIONGRADE',
'    where org_id=v_current_org;',
'',
'    SELECT count(1), max(a.id) into v_pos, v_max_pos',
'    FROM HR_HCF_POSITION a join HR_HCF_ORGSTRUCTUREDTL b on a.orgdtl_id=b.id',
'    WHERE EXISTS(SELECT 1',
'                 FROM HR_HCF_ORGSTRUCTUREHD c',
'                 WHERE org_id=v_ori_org_id',
'                 and b.ORG_STRUCTURE_ID=c.id);',
'             ',
'',
'if v_chk_wiz =''Y'' and v_pos=0 then',
'    ',
'    IF v_wkloc =0 then',
'',
'        :FSP_AFTER_LOGIN_URL := ''f?p=''||:APP_ID||'':2020:''||:APP_SESSION||''::NO::P2020_ID:''||v_current_org;',
'        ',
'    elsif v_org_rule =0  then',
'        SELECT max(id) into v_max_id',
'        FROM HR_HCF_ORG_RULE',
'        where org_id=v_current_org;        ',
'',
'        :FSP_AFTER_LOGIN_URL := ''f?p=''||:APP_ID||'':2021:''||:APP_SESSION||''::NO::P2021_ID:''||v_max_id;',
'        ',
'    elsif v_cyear =0 or v_nis=0 or v_tax=0 then',
'            SELECT max(id) into v_max_nisid',
'            FROM HR_HCF_NISRATE',
'            WHERE org_id=v_current_org;',
'        ',
'        :FSP_AFTER_LOGIN_URL := ''f?p=''||:APP_ID||'':2025:''||:APP_SESSION||''::NO::P2025_ID:''||v_max_nisid;',
'   ',
'    elsif v_orgstructure =0  then',
'           select max(id) into v_max_orgstr',
'           from hr_hcf_orgstructurehd',
'           where org_id=v_current_org;',
'        ',
'         :FSP_AFTER_LOGIN_URL := ''f?p=''||:APP_ID||'':2022:''||:APP_SESSION||''::NO::P2022_ID:''||v_max_orgstr;',
' ',
'   elsif v_job =0 or v_grade=0  then ',
'           :FSP_AFTER_LOGIN_URL := ''f?p=''||:APP_ID||'':2023:''||:APP_SESSION;',
'           ',
'   elsif v_pos = 0 or v_pos_loc =0 then',
'           :FSP_AFTER_LOGIN_URL := ''f?p=''||:APP_ID||'':2024:''||:APP_SESSION;',
'           ',
'   end if;',
' ',
'else',
'',
'           :FSP_AFTER_LOGIN_URL := ''f?p=''||:APP_ID||'':''||v_load_home||'':''||:APP_SESSION||''::NO:::'';',
'    ',
'      ',
'end if;',
'',
'end if;',
'',
'COMMIT;',
'end;',
'',
'----------------------------------------------------------------------------------------------------------------------------------------------------------------',
'',
'procedure my_post_logout',
'AS',
'begin',
'',
'begin',
'  Insert Into tblloginuserlog (App_User, Logout_Date_Time, Session_Id, From_Client, APPLICATION_ID)',
'  values(v(''APP_USER''),current_timestamp,v(''APP_SESSION''),SYS_CONTEXT(''USERENV'',''TERMINAL''), v(''APP_ID''));',
'',
'   delete ',
'   from tblloginuserlog',
'   where upper(App_User)=''NOBODY'';',
'end;',
'   ',
'end my_post_logout;'))
,p_invalid_session_type=>'LOGIN'
,p_post_auth_process=>'POST_AUTHENTICATION'
,p_cookie_name=>'USER_ID'
,p_use_secure_cookie_yn=>'N'
,p_ras_mode=>0
,p_switch_in_session_yn=>'Y'
,p_version_scn=>41800645288433
);
wwv_flow_imp.component_end;
end;
/
