prompt --application/pages/page_04012
begin
--   Manifest
--     PAGE: 04012
--   Manifest End
wwv_flow_imp.component_begin (
 p_version_yyyy_mm_dd=>'2024.11.30'
,p_release=>'24.2.7'
,p_default_workspace_id=>31592798490575853
,p_default_application_id=>112
,p_default_id_offset=>115784133856313705
,p_default_owner=>'TEMPLATE_APPV8'
);
wwv_flow_imp_page.create_page(
 p_id=>4012
,p_name=>'rptRiskAssessment'
,p_step_title=>'General Risk Assessment'
,p_autocomplete_on_off=>'OFF'
,p_group_id=>wwv_flow_imp.id(3170024634159335062)
,p_page_template_options=>'#DEFAULT#'
,p_page_component_map=>'18'
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(3159690309713853578)
,p_plug_name=>'Breadcrumb'
,p_region_template_options=>'#DEFAULT#:t-BreadcrumbRegion--useBreadcrumbTitle'
,p_component_template_options=>'#DEFAULT#'
,p_plug_template=>2531463326621247859
,p_plug_display_sequence=>1
,p_plug_display_point=>'REGION_POSITION_01'
,p_menu_id=>wwv_flow_imp.id(10460765779079194647)
,p_plug_source_type=>'NATIVE_BREADCRUMB'
,p_menu_template_id=>4072363345357175094
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(3285480107883377531)
,p_plug_name=>'Listing of <b>General Risk Assessment </b>'
,p_region_template_options=>'#DEFAULT#:t-Region--scrollBody'
,p_plug_template=>4072358936313175081
,p_plug_display_sequence=>10
,p_query_type=>'SQL'
,p_plug_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'select "ID", ',
'"REVIEW_NUMBER",',
'"REVIEW_DATE",',
'"VERSION_NUMBER",',
'"DATE_REVIEW",',
'"AUTHOURISED_BY",',
'"LOCATION_NAME",',
'"BUILDING_NUMBER",',
'"DATE_ASSESSED",',
'"JWSHC",',
'"OCCUPANCY_CLASSIFICATION",',
'"CONSTRUCTION_CLASS",',
'"PERMIT",',
'"HAVE_PERMIT",',
'"EPA_LICENCE_NUM",',
'"L_ISSUE_DATE",',
'"EXPIRY_DATE",',
'"COPY_ATTACHED",',
'"FIRE_CER_NUM",',
'"CER_ISSUED_DATE",',
'"F_EXPIRY_DATE",',
'"ELEC_CER_NUM",',
'"ELEC_ISSUE_DATE",',
'"ELEC_EXPIRY_DATE",',
'"NUM_FLOOR",',
'"AREA_FIRST_FLOOR",',
'"OCCU_FIRST_FLOOR",',
'"AREA_SECO_FLOOR",',
'"OCCU_SECO_FLOOR",',
'"AREA_THIR_FLOOR",',
'"OCCU_THIR_FLOOR",',
'"AREA_FOUR_FLOOR",',
'"OCCU_FOUR_FLOOR",',
'"BUILD_CAPACITY"',
'from "#OWNER#"."HR_HS_RISK_ASSESSMENT" ',
'  ',
''))
,p_plug_source_type=>'NATIVE_IR'
);
wwv_flow_imp_page.create_worksheet(
 p_id=>wwv_flow_imp.id(3285480566510377532)
,p_name=>'Report 1'
,p_max_row_count=>'1000000'
,p_max_row_count_message=>'The maximum row count for this report is #MAX_ROW_COUNT# rows.  Please apply a filter to reduce the number of records in your query.'
,p_no_data_found_message=>'No data found.'
,p_allow_save_rpt_public=>'Y'
,p_show_nulls_as=>'-'
,p_pagination_type=>'ROWS_X_TO_Y'
,p_pagination_display_pos=>'BOTTOM_RIGHT'
,p_show_display_row_count=>'Y'
,p_report_list_mode=>'TABS'
,p_lazy_loading=>false
,p_show_detail_link=>'N'
,p_show_rows_per_page=>'N'
,p_show_notify=>'Y'
,p_download_formats=>'CSV:HTML:XLSX:PDF'
,p_enable_mail_download=>'Y'
,p_owner=>'DIANTEC'
,p_internal_uid=>205373476300525711
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(3163956358873728929)
,p_db_column_name=>'ID'
,p_display_order=>1
,p_column_identifier=>'A'
,p_column_label=>'Edit'
,p_column_link=>'f?p=&APP_ID.:4013:&SESSION.::&DEBUG.:RP,4013:P4013_ID:#ID#'
,p_column_linktext=>'<img src="#IMAGE_PREFIX#app_ui/img/icons/apex-edit-pencil-alt.png" class="apex-edit-pencil-alt" alt="">'
,p_column_type=>'NUMBER'
,p_heading_alignment=>'LEFT'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(3163956004770728929)
,p_db_column_name=>'REVIEW_NUMBER'
,p_display_order=>2
,p_column_identifier=>'B'
,p_column_label=>'Review Number'
,p_column_type=>'NUMBER'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(3163955587743728929)
,p_db_column_name=>'REVIEW_DATE'
,p_display_order=>3
,p_column_identifier=>'C'
,p_column_label=>'Review Date'
,p_column_type=>'DATE'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(3163955213944728928)
,p_db_column_name=>'VERSION_NUMBER'
,p_display_order=>4
,p_column_identifier=>'D'
,p_column_label=>'Version Number'
,p_column_type=>'NUMBER'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(3163954758808728928)
,p_db_column_name=>'DATE_REVIEW'
,p_display_order=>5
,p_column_identifier=>'E'
,p_column_label=>'Date Review'
,p_column_type=>'DATE'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(3163954393528728928)
,p_db_column_name=>'AUTHOURISED_BY'
,p_display_order=>6
,p_column_identifier=>'F'
,p_column_label=>'Authourised By'
,p_column_type=>'STRING'
,p_display_text_as=>'LOV_ESCAPE_SC'
,p_heading_alignment=>'LEFT'
,p_rpt_named_lov=>wwv_flow_imp.id(3326578119485849578)
,p_rpt_show_filter_lov=>'1'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(3163954010301728927)
,p_db_column_name=>'LOCATION_NAME'
,p_display_order=>7
,p_column_identifier=>'G'
,p_column_label=>'Location Name'
,p_column_type=>'STRING'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(3163953553832728927)
,p_db_column_name=>'BUILDING_NUMBER'
,p_display_order=>8
,p_column_identifier=>'H'
,p_column_label=>'Building Number'
,p_column_type=>'NUMBER'
,p_heading_alignment=>'LEFT'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(3163953205542728927)
,p_db_column_name=>'DATE_ASSESSED'
,p_display_order=>9
,p_column_identifier=>'I'
,p_column_label=>'Date Assessed'
,p_column_type=>'DATE'
,p_display_text_as=>'HIDDEN'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(3163952840470728927)
,p_db_column_name=>'JWSHC'
,p_display_order=>11
,p_column_identifier=>'K'
,p_column_label=>'Jwshc'
,p_column_type=>'STRING'
,p_display_text_as=>'HIDDEN'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(3163952432862728926)
,p_db_column_name=>'OCCUPANCY_CLASSIFICATION'
,p_display_order=>12
,p_column_identifier=>'L'
,p_column_label=>'Occupancy Classification'
,p_column_type=>'STRING'
,p_display_text_as=>'HIDDEN'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(3163952011155728926)
,p_db_column_name=>'CONSTRUCTION_CLASS'
,p_display_order=>13
,p_column_identifier=>'M'
,p_column_label=>'Construction Class'
,p_column_type=>'STRING'
,p_display_text_as=>'HIDDEN'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(3163951550109728925)
,p_db_column_name=>'PERMIT'
,p_display_order=>14
,p_column_identifier=>'N'
,p_column_label=>'Permit'
,p_column_type=>'STRING'
,p_display_text_as=>'HIDDEN'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(3163951165539728925)
,p_db_column_name=>'HAVE_PERMIT'
,p_display_order=>15
,p_column_identifier=>'O'
,p_column_label=>'Have Permit'
,p_column_type=>'STRING'
,p_display_text_as=>'HIDDEN'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(3163950748909728925)
,p_db_column_name=>'EPA_LICENCE_NUM'
,p_display_order=>16
,p_column_identifier=>'P'
,p_column_label=>'Epa Licence Num'
,p_column_type=>'NUMBER'
,p_display_text_as=>'HIDDEN'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(3163950403299728924)
,p_db_column_name=>'L_ISSUE_DATE'
,p_display_order=>17
,p_column_identifier=>'Q'
,p_column_label=>'L Issue Date'
,p_column_type=>'DATE'
,p_display_text_as=>'HIDDEN'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(3163950008221728924)
,p_db_column_name=>'EXPIRY_DATE'
,p_display_order=>18
,p_column_identifier=>'R'
,p_column_label=>'Expiry Date'
,p_column_type=>'DATE'
,p_display_text_as=>'HIDDEN'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(3163949570978728924)
,p_db_column_name=>'COPY_ATTACHED'
,p_display_order=>19
,p_column_identifier=>'S'
,p_column_label=>'Copy Attached'
,p_column_type=>'STRING'
,p_display_text_as=>'HIDDEN'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(3163949153639728924)
,p_db_column_name=>'FIRE_CER_NUM'
,p_display_order=>20
,p_column_identifier=>'T'
,p_column_label=>'Fire Cer Num'
,p_column_type=>'NUMBER'
,p_display_text_as=>'HIDDEN'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(3163948819782728923)
,p_db_column_name=>'CER_ISSUED_DATE'
,p_display_order=>21
,p_column_identifier=>'U'
,p_column_label=>'Cer Issued Date'
,p_column_type=>'DATE'
,p_display_text_as=>'HIDDEN'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(3163948412293728923)
,p_db_column_name=>'F_EXPIRY_DATE'
,p_display_order=>22
,p_column_identifier=>'V'
,p_column_label=>'F Expiry Date'
,p_column_type=>'DATE'
,p_display_text_as=>'HIDDEN'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(3163947983757728923)
,p_db_column_name=>'ELEC_CER_NUM'
,p_display_order=>23
,p_column_identifier=>'W'
,p_column_label=>'Elec Cer Num'
,p_column_type=>'NUMBER'
,p_display_text_as=>'HIDDEN'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(3163947622577728922)
,p_db_column_name=>'ELEC_ISSUE_DATE'
,p_display_order=>24
,p_column_identifier=>'X'
,p_column_label=>'Elec Issue Date'
,p_column_type=>'DATE'
,p_display_text_as=>'HIDDEN'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(3163947218006728922)
,p_db_column_name=>'ELEC_EXPIRY_DATE'
,p_display_order=>25
,p_column_identifier=>'Y'
,p_column_label=>'Elec Expiry Date'
,p_column_type=>'DATE'
,p_display_text_as=>'HIDDEN'
,p_tz_dependent=>'N'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(3163946810666728922)
,p_db_column_name=>'NUM_FLOOR'
,p_display_order=>26
,p_column_identifier=>'Z'
,p_column_label=>'Num Floor'
,p_column_type=>'NUMBER'
,p_display_text_as=>'HIDDEN'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(3163946401072728922)
,p_db_column_name=>'AREA_FIRST_FLOOR'
,p_display_order=>27
,p_column_identifier=>'AA'
,p_column_label=>'Area First Floor'
,p_column_type=>'STRING'
,p_display_text_as=>'HIDDEN'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(3163946113048728921)
,p_db_column_name=>'OCCU_FIRST_FLOOR'
,p_display_order=>28
,p_column_identifier=>'AB'
,p_column_label=>'Occu First Floor'
,p_column_type=>'NUMBER'
,p_display_text_as=>'HIDDEN'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(3163945679246728921)
,p_db_column_name=>'AREA_SECO_FLOOR'
,p_display_order=>29
,p_column_identifier=>'AC'
,p_column_label=>'Area Seco Floor'
,p_column_type=>'STRING'
,p_display_text_as=>'HIDDEN'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(3163945267812728921)
,p_db_column_name=>'OCCU_SECO_FLOOR'
,p_display_order=>30
,p_column_identifier=>'AD'
,p_column_label=>'Occu Seco Floor'
,p_column_type=>'NUMBER'
,p_display_text_as=>'HIDDEN'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(3163944936834728921)
,p_db_column_name=>'AREA_THIR_FLOOR'
,p_display_order=>31
,p_column_identifier=>'AE'
,p_column_label=>'Area Thir Floor'
,p_column_type=>'STRING'
,p_display_text_as=>'HIDDEN'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(3163944507915728920)
,p_db_column_name=>'OCCU_THIR_FLOOR'
,p_display_order=>32
,p_column_identifier=>'AF'
,p_column_label=>'Occu Thir Floor'
,p_column_type=>'NUMBER'
,p_display_text_as=>'HIDDEN'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(3163944092606728920)
,p_db_column_name=>'AREA_FOUR_FLOOR'
,p_display_order=>33
,p_column_identifier=>'AG'
,p_column_label=>'Area Four Floor'
,p_column_type=>'STRING'
,p_display_text_as=>'HIDDEN'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(3163943662695728920)
,p_db_column_name=>'OCCU_FOUR_FLOOR'
,p_display_order=>34
,p_column_identifier=>'AH'
,p_column_label=>'Occu Four Floor'
,p_column_type=>'NUMBER'
,p_display_text_as=>'HIDDEN'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_column(
 p_id=>wwv_flow_imp.id(3163943320515728919)
,p_db_column_name=>'BUILD_CAPACITY'
,p_display_order=>35
,p_column_identifier=>'AI'
,p_column_label=>'Build Capacity'
,p_column_type=>'STRING'
,p_display_text_as=>'HIDDEN'
,p_use_as_row_header=>'N'
);
wwv_flow_imp_page.create_worksheet_rpt(
 p_id=>wwv_flow_imp.id(3285494993108377987)
,p_application_user=>'APXWS_DEFAULT'
,p_report_seq=>10
,p_report_alias=>'746520'
,p_status=>'PUBLIC'
,p_is_default=>'Y'
,p_report_columns=>'ID:REVIEW_NUMBER:REVIEW_DATE:VERSION_NUMBER:DATE_REVIEW:AUTHOURISED_BY:LOCATION_NAME:BUILDING_NUMBER:DATE_ASSESSED:JWSHC:OCCUPANCY_CLASSIFICATION:CONSTRUCTION_CLASS:PERMIT:HAVE_PERMIT:EPA_LICENCE_NUM:L_ISSUE_DATE:EXPIRY_DATE:COPY_ATTACHED:FIRE_CER_NU'
||'M:CER_ISSUED_DATE:F_EXPIRY_DATE:ELEC_CER_NUM:ELEC_ISSUE_DATE:ELEC_EXPIRY_DATE:NUM_FLOOR:AREA_FIRST_FLOOR:OCCU_FIRST_FLOOR:AREA_SECO_FLOOR:OCCU_SECO_FLOOR:AREA_THIR_FLOOR:OCCU_THIR_FLOOR:AREA_FOUR_FLOOR:OCCU_FOUR_FLOOR:BUILD_CAPACITY'
);
wwv_flow_imp_page.create_page_button(
 p_id=>wwv_flow_imp.id(3163942538307728919)
,p_button_sequence=>10
,p_button_plug_id=>wwv_flow_imp.id(3159690309713853578)
,p_button_name=>'CANCEL'
,p_button_action=>'REDIRECT_PAGE'
,p_button_template_options=>'#DEFAULT#:t-Button--primary:t-Button--iconRight'
,p_button_template_id=>2082829544945815391
,p_button_image_alt=>'Return'
,p_button_position=>'EDIT'
,p_button_alignment=>'RIGHT'
,p_button_redirect_url=>'f?p=&APP_ID.:1:&SESSION.::&DEBUG.:RP::'
,p_icon_css_classes=>'fa-hand-o-left'
);
wwv_flow_imp_page.create_page_button(
 p_id=>wwv_flow_imp.id(3163942089621728918)
,p_button_sequence=>20
,p_button_plug_id=>wwv_flow_imp.id(3159690309713853578)
,p_button_name=>'CREATE'
,p_button_action=>'REDIRECT_PAGE'
,p_button_template_options=>'#DEFAULT#:t-Button--success:t-Button--iconRight'
,p_button_template_id=>2082829544945815391
,p_button_image_alt=>'Add New'
,p_button_position=>'EDIT'
,p_button_alignment=>'RIGHT'
,p_button_redirect_url=>'f?p=&APP_ID.:4013:&SESSION.::&DEBUG.:4013'
,p_icon_css_classes=>'fa-plus-square'
);
wwv_flow_imp.component_end;
end;
/
