name: Deploy APEX Application

on:
  # Allow manual triggering
  workflow_dispatch:  
    inputs:
      # git-ref:
      #   description: 'Git commit SHA or tag to deploy (for rollbacks)'
      #   required: false
      #   default: ''
      branch:
        description: 'The branch to deploy from'
        required: true
        default: 'develop' # Default to the development branch for convenience

  # Trigger the workflow on pushes to these specific branches
  push:
    branches:
      - main
      - staging
      - develop
# env:
#   GITHUB_USER: ${{ github.actor }}
#   GITHUB_BRANCH: ${{ github.ref_name }}
#   GITHUB_BRANCH_REF: ${{ github.ref }}
#   DEPLOY_TIMESTAMP: ${{ github.run_id }}
  
permissions:
  contents: write  # Grant write permissions to the GITHUB_TOKEN

jobs:
  deploy-to-apex:
    runs-on: ubuntu-latest
    
    env:
      ENVIRONMENT: ${{ github.ref_name }}
      DB_URL: ${{ vars.DB_URL }}
      DB_USER: ${{ vars.DB_USER }}
      APP_ID: ${{ vars.APP_ID }}
      WKSPACE: ${{ vars.WKSPACE }}
      SCHEMA: ${{ vars.SCHEMA }}      
      USER: ${{ github.actor }}     


    # Dynamically set the environment based on the branch name
    environment:
      name: ${{ (github.ref_name == 'main' && 'Production') || (github.ref_name == 'staging' && 'Staging') || 'Development' }}

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      - name: 1. Substitute variables into SQL script
        run: |
          # Reads the template and outputs a processed file
          envsubst < deploy_apex_app.sql.template > deploy_apex_app.sql

          echo "--- Generated SQL Script ---"
          cat deploy_apex_app.sql
          echo "--------------------------"


      # Set up Java (required for SQLcl)
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      # Download and set up SQLcl
      - name: Set up SQLcl
        run: |
          wget https://download.oracle.com/otn_software/java/sqldeveloper/sqlcl-latest.zip
          unzip -o sqlcl-latest.zip
          echo "$(pwd)/sqlcl/bin" >> $GITHUB_PATH

      - name: Deploy APEX App Operation
        env:
          # These secrets are populated from the GitHub Environment you configured
          GITHUB_TOKEN: ${{ secrets.TOK }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          ENVIRONMENT: ${{ github.ref_name }}
          DB_URL: ${{ vars.DB_URL }}
          DB_USER: ${{ vars.DB_USER }}
          APP_ID: ${{ vars.APP_ID }}
          WKSPACE: ${{ vars.WKSPACE }}
          SCHEMA: ${{ vars.SCHEMA }}
        run: |
          echo "${{ vars.ATP_WALLET_DEV }}" | base64 --decode > Wallet_DEVENV.zip
          sql  -cloudconfig  Wallet_DEVENV.zip $DB_USER/$DB_PASSWORD@$DB_URL @deploy_apex_app.sql

